### ISSUE TITLE
ProblemStatement

### ISSUE THREAD

**Issue by icbicket** [icbicket/DataAnalysis#1]
Please review my [problem statement](https://github.com/icbicket/SpectrumImageAnalysisPy/tree/SpectrumImageAnalysisPy_dev/Doc/ProblemStatement/ProblemStatement.pdf) for the course!

**Comment by smiths** [comment]
Hello @icbicket.  Your problem statement looks good.  I added a comment to it related to the LaTeX formatting.  I also modified your .gitignore file so that *.DS_Store doesn't show up on my Mac as potential files to add.

Your project includes graphics, as part of your visualization.  For other students I am hesitant to include graphics, since they are often too much work for a 13 week course, but given that you already have a successful implementation, this shouldn't be a problem in your case.
