### ISSUE TITLE
SRS: Semicolons

### ISSUE THREAD

**Issue by keshavd** [icbicket/DataAnalysis#4]
I noticed with the lists, you have a tendency to end each statement with a semicolon (Section 4.1, 5.1.1., some of 5.21 etc)

I found this a bit distracting. I think this is habit from programming. I had the same thing in my first version of my Latex document. Maybe remove the semicolons for a cleaner look?

**Comment by icbicket** [comment]
Thanks for the comment. In some cases, using a semicolon to terminate list items is a correct use of semicolons (not from programming, I inherited this from high school English classes :). You are right that I should be more careful in which lists I use semicolons in, as it is not always appropriate. Generally, if any of the list items are complicated phrases and you would otherwise use a comma to separate them, the semicolon should be used. If they're full sentences (which some of mine are), there should be periods instead, so thank you for pointing this out. I have modified some of the lists (and made others into tables) here: fd66bd290a4c011f271fa91370a4fc5893292cbe.
