### ISSUE TITLE
SRS: T2 Signal

### ISSUE THREAD

**Issue by keshavd** [icbicket/DataAnalysis#5]
This theoretical model was well described.

I'm not too familiar with discrete and continuous mathematics, and I'm not sure if this relevant.

Would it be within the scope to show how the continuous model of the signal is converted to the discretized version? As in what assumptions were made?

I assume this is described in the reference by JM Zuo. 

I just thought it would be insightful to see how the two equations in TM2 are mathematically linked.

**Comment by icbicket** [comment]
You have a good point. JM Zuo does not mathematically provide the translation between continuous and discrete, and I'm not sure myself how the mathematics would look. The continuous signal can be thought of as the signal hitting the camera: it can hit at any location; the discrete signal can be thought of as the signal that the camera sees hitting it: now the location is categorized into pixels, so we must deal with discretized space (pixels), rather than continuous space. The conversion between continuous and discrete is done by the hardware of the camera. I hope this makes some sense; I have added more description of the difference and translation between continuous and discrete into the text for T2 (e9d395e34d9534afff1f0d6d7c010c467760e49e).
